"""add project_date sort key to projects

Revision ID: 5abb7a694240
Revises: e3304ca4b1c7
Create Date: 2026-06-04 12:09:38.803851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5abb7a694240'
down_revision: Union[str, None] = 'e3304ca4b1c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('project_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'project_date')
    # ### end Alembic commands ###
