"""add github_stars and github_forks to projects

Revision ID: be76926e7e7f
Revises: e0ac08911742
Create Date: 2026-06-04 10:33:10.917215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be76926e7e7f'
down_revision: Union[str, None] = 'e0ac08911742'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('github_stars', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('github_forks', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'github_forks')
    op.drop_column('projects', 'github_stars')
    # ### end Alembic commands ###
