"""create projects and posts

Revision ID: e0ac08911742
Revises: 
Create Date: 2026-06-04 08:53:48.342259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e0ac08911742'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('title_en', sa.String(length=200), nullable=False),
    sa.Column('title_zh', sa.String(length=200), nullable=False),
    sa.Column('excerpt_en', sa.Text(), nullable=False),
    sa.Column('excerpt_zh', sa.Text(), nullable=False),
    sa.Column('body_en', sa.Text(), nullable=False),
    sa.Column('body_zh', sa.Text(), nullable=False),
    sa.Column('cover_image', sa.String(length=500), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('reading_minutes', sa.Integer(), nullable=False),
    sa.Column('meta_title_en', sa.String(length=200), nullable=True),
    sa.Column('meta_title_zh', sa.String(length=200), nullable=True),
    sa.Column('meta_description_en', sa.Text(), nullable=True),
    sa.Column('meta_description_zh', sa.Text(), nullable=True),
    sa.Column('og_image', sa.String(length=500), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_slug'), 'posts', ['slug'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('title_en', sa.String(length=200), nullable=False),
    sa.Column('title_zh', sa.String(length=200), nullable=False),
    sa.Column('summary_en', sa.Text(), nullable=False),
    sa.Column('summary_zh', sa.Text(), nullable=False),
    sa.Column('body_en', sa.Text(), nullable=False),
    sa.Column('body_zh', sa.Text(), nullable=False),
    sa.Column('cover_image', sa.String(length=500), nullable=True),
    sa.Column('tech', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('links', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('period', sa.String(length=80), nullable=True),
    sa.Column('role_en', sa.String(length=160), nullable=True),
    sa.Column('role_zh', sa.String(length=160), nullable=True),
    sa.Column('meta_title_en', sa.String(length=200), nullable=True),
    sa.Column('meta_title_zh', sa.String(length=200), nullable=True),
    sa.Column('meta_description_en', sa.Text(), nullable=True),
    sa.Column('meta_description_zh', sa.Text(), nullable=True),
    sa.Column('og_image', sa.String(length=500), nullable=True),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_posts_slug'), table_name='posts')
    op.drop_table('posts')
    # ### end Alembic commands ###
