"""add video_url to projects

Revision ID: e3304ca4b1c7
Revises: be76926e7e7f
Create Date: 2026-06-04 11:17:54.640078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3304ca4b1c7'
down_revision: Union[str, None] = 'be76926e7e7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('video_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'video_url')
    # ### end Alembic commands ###
